Update dependency xmldom
Switching from package `xmldom` to `@xmldom/xmldom`, which resolves the security issue present in latest xmldom version 0.6.0:
https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q

The reason is that the maintainers were forced to switch to a scoped package since 0.7.0:
 https://github.com/xmldom/xmldom/issues/271

- I used node 12 to run `npm install`.
- I executed `npm run test` on my machine, but it failed because of some missing file:
```
[...]
> seriate@4.0.0 test:only /run/media/karfau/hdd-data/dev/seriate
> NODE_ENV=test mocha --exit -r spec/init -R spec 'spec/**/*.spec.js'

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

Error: Cannot find module './local-config.json'
Require stack:
- /run/media/karfau/hdd-data/dev/seriate/spec/integration/one-connection.spec.js
[...]
```
- I executed `npm run test:ci` onmy machine without failure

I'm one of the xmldom maintainers. Don't hesitate to ask me questions.